

OLX_PATH_LOCATION = '''/html/body[@class='detailpage t-new_sidebar']/div[@id='innerLayout']/section[@id='body-container']/div[@class='wrapper']/div[@id='offer_active']/div[@class='clr offerbody']/div[@class='offercontent fleft rel ']/div[@class='offercontentinner offer__innerbox']/div[@id='offerdescription']/div[@class='offer-titlebox']/div[@class='offer-titlebox__details']/a[@class='show-map-link']/strong/text()'''
OLX_PATH_ADDED = '''/html/body[@class='detailpage t-new_sidebar']/div[@id='innerLayout']/section[@id='body-container']/div[@class='wrapper']/div[@id='offer_active']/div[@class='clr offerbody']/div[@class='offercontent fleft rel ']/div[@class='offercontentinner offer__innerbox']/div[@id='offerdescription']/div[@class='offer-titlebox']/div[@class='offer-titlebox__details']/em/text()'''
OLX_PATH_INTERNAL_ID = '''/html/body[@class='detailpage t-new_sidebar']/div[@id='innerLayout']/section[@id='body-container']/div[@class='wrapper']/div[@id='offer_active']/div[@class='clr offerbody']/div[@class='offercontent fleft rel ']/div[@class='offercontentinner offer__innerbox']/div[@id='offerdescription']/div[@class='offer-titlebox']/div[@class='offer-titlebox__details']/em/small/text()'''
OLX_PATH_DESCRIPTION = '''/html/body[@class='detailpage t-new_sidebar']/div[@id='innerLayout']/section[@id='body-container']/div[@class='wrapper']/div[@id='offer_active']/div[@class='clr offerbody']/div[@class='offercontent fleft rel ']/div[@class='offercontentinner offer__innerbox']/div[@id='offerdescription']/div[@class='clr descriptioncontent marginbott20']/div[@id='textContent']/p[@class='pding10 lheight20 large']/text()'''
OLX_PATH_PHOTHOS = '''//div[@class="photo-glow"]/img/@src'''
OLX_PATH_PRICE = '''//meta[@name="description"]/@content'''
OLX_PATH_ATTRIBUTES = '''//table[@class="details fixed marginbott20 margintop5 full"]'''
OLX_PATH_SURFACE = '''/html/body[@class='detailpage t-new_sidebar']/div[@id='innerLayout']/section[@id='body-container']/div[@class='wrapper']/div[@id='offer_active']/div[@class='clr offerbody']/div[@class='offercontent fleft rel ']/div[@class='offercontentinner offer__innerbox']/div[@id='offerdescription']/div[@class='clr descriptioncontent marginbott20']/table[@class='details fixed marginbott20 margintop5 full']/tbody/tr[3]/td[@class='col'][1]/table[@class='item']/tbody/tr/td[@class='value']/strong/text()'''
OLX_NEXT_PAGE_PATH = '''/html/body[@class='offersview standard']/div[@id='innerLayout']/div[@id='listContainer']/section[@id='body-container']/div[@class='wrapper'][2]/div[@class='content']/div[@class='pager rel clr']/span[@class='fbold next abs large']/a/@href'''
OLX_SURFACE_BUCKET = '''/html/body[@class='offersview standard']/div[@id='innerLayout']/div[@id='listContainer']/section[@id='body-container']/div[@class='wrapper'][2]/div[@class='content']/div[@class='pager rel clr']/span[@class='fbold next abs large']/a/@href'''
